import adapter from '@sveltejs/adapter-static';

/** @type {import('@sveltejs/kit').Config} */
const config = {
	kit: {
		adapter: adapter(),
		prerender: {
			// OG images are generated by the screenshot pipeline post-deploy — ignore missing at build time
			handleHttpError: ({ path, message }) => {
				if (path.startsWith('/og/')) return;
				throw new Error(message);
			}
		}
	}
};

export default config;
